#endpoints:
#  enabled: false
info:
  component: backend-arquetipo
spring:
  application:
    name: backend-arquetipo
  profiles:
    active: dev
  datasource:
    postgresql:
      write:
        url: jdbc:postgresql://localhost:5432/testbd?currentSchema=public
        driverClassName: org.postgresql.Driver
        username: postgres
        password: secret
    mysql:
      read:
        url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true
        driverClassName: com.mysql.cj.jdbc.Driver
        username: root
        password: root
  jpa:
    postgresql:
      write:
        databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    mysql:
      read:
        databasePlatform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
server:
  servlet:
    context-path: "/backend-arquetipo"
  port: 8080

kafka:
  bootstrap-servers: localhost:9092
  consumer:
    backendArquetipoGroupId: backendArquetipoGroup

resilience4j:
  retry:
    instances:
      pruebaRetry:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - java.lang.Throwable